# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates: https://malesforfemalesllc.atlassian.net/gateway/api/compass/v1/webhooks/bdc563e6-fae2-4fb9-a320-88e7dbc2d636
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
https://go.atlassian.com/compass-yml-format
